import { Button, Card } from "@/components/ui";
import { AuthMarketingConsent } from "@/components/AuthMarketingConsent";

const authErrors: Record<string, string> = {
  "supabase-auth-not-configured": "Supabase auth keys are missing in the app environment.",
  "google-oauth-not-configured": "Google OAuth is not enabled in Supabase, or the Google redirect URL is missing.",
  "auth-callback-failed": "Google did not return an auth code.",
  "auth-session-failed": "Supabase could not create a session from the Google callback."
};

export default async function LoginPage({ searchParams }: { searchParams?: Promise<{ error?: string; demo?: string }> }) {
  const params = await searchParams;
  const error = params?.error ? authErrors[params.error] : null;
  const showDemo = params?.demo === "1" || process.env.SHOW_DEMO_LOGIN === "true";
  return <main className="flex min-h-screen items-center justify-center bg-[radial-gradient(circle_at_76%_12%,rgba(22,119,255,.28)_0,transparent_30%),linear-gradient(180deg,#050a18,#08111f)] p-8"><Card className="w-full max-w-[480px] !border-white/10 !bg-white/10 p-9 !text-white shadow-[0_30px_90px_rgba(0,0,0,.32)]"><div className="mb-6 inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-white shadow-[0_18px_48px_rgba(22,119,255,.22)]"><img className="h-9 w-9" alt="Reachlyst" src="/reachlyst-logo-r-blue.png" /></div><h1 className="text-4xl font-extrabold leading-none text-white">Log in</h1><p className="mt-3 text-sm font-semibold leading-6 text-white/70">Continue to your Sales Navigator outreach workspace.</p>{error ? <div className="mt-5 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-extrabold leading-6 text-rose-800">{error}</div> : null}<form className="my-5 grid gap-3"><input className="min-h-12 rounded-lg border border-white/15 bg-white/10 px-3 text-white outline-none placeholder:text-white/50" placeholder="Email" defaultValue="" /><input className="min-h-12 rounded-lg border border-white/15 bg-white/10 px-3 text-white outline-none placeholder:text-white/50" placeholder="Password" type="password" defaultValue="" /><Button href="/app/dashboard">Log in with email</Button></form><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-xs font-extrabold uppercase text-white/45 before:h-px before:bg-white/15 before:content-[''] after:h-px after:bg-white/15 after:content-['']"><span>or</span></div><AuthMarketingConsent action="Log in" />{showDemo ? <div className="my-5 grid gap-1.5 rounded-lg border border-blue-300/20 bg-blue-300/10 p-4 text-white"><strong>Private demos</strong><span className="font-mono text-sm text-white/70">Workspace demo: demo@reachlyst.local</span><a className="my-1 inline-flex min-h-10 items-center justify-center rounded-lg border border-blue-200/20 bg-blue-300/15 px-3 py-2 font-extrabold text-blue-100 transition hover:bg-blue-300/25" href="/api/demo-login?role=workspace_owner">Open workspace demo</a><span className="font-mono text-sm text-white/70">Super admin demo: admin@reachlyst.local</span><a className="my-1 inline-flex min-h-10 items-center justify-center rounded-lg border border-blue-200/20 bg-blue-300/15 px-3 py-2 font-extrabold text-blue-100 transition hover:bg-blue-300/25" href="/api/demo-login?role=super_admin">Open super admin demo</a></div> : null}<p className="mt-5 text-center text-sm font-semibold text-white/70">No account? <a className="font-extrabold text-blue-300" href="/signup">Sign up</a></p></Card></main>;
}
