import Link from "next/link";
import { Badge, Card, SearchInput } from "@/components/ui";
import { CopyButton } from "@/components/CopyButton";
import { truncateMiddle } from "@/lib/format";
import { getDashboardData } from "@/lib/store";

export const dynamic = "force-dynamic";

export default async function SearchesPage() {
  const { searches } = await getDashboardData();
  return <div className="grid gap-4"><div className="flex items-center justify-between gap-4"><div><h1 className="text-3xl font-extrabold text-ink">Searches</h1><p className="mt-1 text-sm font-semibold text-muted">{searches.length} Sales Navigator searches synced from the extension.</p></div></div><SearchInput placeholder="Search campaigns" /><Card className="overflow-x-auto p-0"><table className="min-w-[860px] w-full border-collapse"><thead><tr className="text-left text-xs uppercase text-muted"><th className="border-b border-line p-4">Search</th><th className="border-b border-line p-4">Leads</th><th className="border-b border-line p-4">Good fit</th><th className="border-b border-line p-4">Invited</th><th className="border-b border-line p-4">Replied</th><th className="border-b border-line p-4">Last synced</th></tr></thead><tbody>{searches.map((search) => <tr className="group relative cursor-pointer transition hover:bg-slate-50 hover:shadow-[inset_3px_0_0_#8aa39a]" key={search.id}><td className="border-b border-line p-4 align-top"><Link className="static font-extrabold text-accent-strong after:absolute after:inset-0 after:z-[1]" href={`/app/searches/${search.id}`}>{search.name}</Link><div className="relative z-[2] mt-2 flex min-w-0 items-center gap-2"><span className="inline-block max-w-[360px] overflow-hidden text-ellipsis whitespace-nowrap font-mono text-xs text-muted" title={search.url}>{truncateMiddle(search.url)}</span><CopyButton value={search.url} /></div></td><td className="border-b border-line p-4 align-top text-sm font-bold text-ink">{search.leads}</td><td className="border-b border-line p-4 align-top"><Badge tone="good">{search.good}</Badge></td><td className="border-b border-line p-4 align-top text-sm font-bold text-ink">{search.invited}</td><td className="border-b border-line p-4 align-top text-sm font-bold text-ink">{search.replied}</td><td className="border-b border-line p-4 align-top text-sm font-semibold text-muted">{search.synced ?? "Not synced"}</td></tr>)}</tbody></table></Card></div>;
}
